obj-$(CONFIG_MACH_APQ8064_DUMA) += board-duma.o \
	board-duma-gpiomux.o \
	board-duma-pmic.o \
	board-duma-camera.o \
	board-duma-gpu.o \
	board-duma-regulator.o \
	board-duma-display.o \
	board-duma-storage.o
